version: "3.8"
services:
  server:
    build:
      context: ./server
    container_name: coffee-art-ai-server
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    networks:
      - coffee-art-ai-network

  client:
    build:
      context: ./client
    container_name: coffee-art-ai-client
    restart: always
    ports:
      - "3000:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - coffee-art-ai-network

networks:
  coffee-art-ai-network:
    driver: bridge
