const domesticAnimals = [
  'Dog',
  'Cat',
  'Horse',
  'Cow',
  'Pig',
  'Chicken',
  'Sheep',
  'Goat',
  'Duck',
  'Goose',
  'Turkey',
  'Rabbit',
  'Guinea pig',
  'Hamster',
  'Gerbil',
  'Ferret',
  'Llama',
  'Alpaca',
  'Donkey',
  'Mule',
  'Canary',
  'Budgerigar',
  'Goldfish',
  'Koi fish',
  'Pigeon',
  'Silkworm',
  'Honeybee',
  'Yak',
  'Water buffalo',
  'Camel',
  'Fancy rat',
]

const wildAnimals = [
  'Lion',
  'Tiger',
  'Elephant',
  'Wolf',
  'Fox',
  'Bear',
  'Deer',
  'Eagle',
  'Hawk',
  'Owl',
  'Snake',
  'Lizard',
  'Frog',
  'Toad',
  'Fish',
  'Shark',
  'Dolphin',
  'Whale',
  'Monkey',
  'Gorilla',
  'Chimpanzee',
  'Zebra',
  'Giraffe',
  'Kangaroo',
  'Koala',
  'Beaver',
  'Otter',
  'Squirrel',
  'Rabbit',
  'Hedgehog',
  'Bat',
]

const funnyAssociations = [
  'wearing a tutu made of lettuce',
  'sipping tea from a bottle cap',
  'using a thimble as a helmet',
  'sporting tiny aviator goggles',
  'balancing a spoon on its nose',
  'hiding in a slipper',
  'conducting an orchestra of mice',
  'holding a balloon shaped like a peanut',
  'dancing in a cereal bowl',
  'stuck inside a roll of tape',
  'knitting with spaghetti noodles',
  'napping in a tissue box',
  'wearing a cape made from a napkin',
  'painting with its tail',
  'trying to lasso a marble',
  'hosting a tea party for ants',
  'pretending to be a garden gnome',
  'posing in front of a fan like a supermodel',
  'tap dancing on a cracker',
  'wearing glasses made from paperclips',
  'taking selfies with a jellybean phone',
  'playing chess with acorns',
  'wearing mismatched socks as pants',
  'building a sandcastle in a potted plant',
  'floating in a teacup boat',
  'tangled in spaghetti noodles',
  'investigating footprints in flour',
  'hiding behind a playing card',
  'disguised as a potato',
  'riding a skateboard made of butter',
  'pretending to be a sushi roll',
  'wearing a marshmallow as a helmet',
  'pretending to DJ on a record-sized cookie',
  'ziplining on floss',
  'painting graffiti on a soda can',
  'doing yoga on a sponge',
  'ice skating on a frozen plate',
  'launching a paperclip catapult',
  'hiding treasure in a sock drawer',
  'surfing on a slice of cucumber',
  'polishing a button like a trophy',
  'caught in a slinky trap',
  'roasting a mini marshmallow over a candle',
  'directing traffic with a toothpick wand',
  'wearing mittens made from cotton balls',
  'playing the harmonica with a serious face',
  'wrapped in toilet paper like a mummy',
  'chasing a runaway jellybean',
  'cheering with pom-poms made of yarn',
  'holding a press conference with LEGO microphones',
  'oversized sunglasses',
  'wearing a tiny graduation cap',
  'with a carrot-shaped microphone',
  'hoarding miniature traffic cones',
  'sporting a monocle and top hat',
  'pushing a shopping cart filled with seeds',
  'wearing rain boots and holding an umbrella',
  'with a tiny hard hat',
  'wearing a colorful scarf',
  'with a pearl necklace',
  'wearing a tiny cowboy hat',
  'with a rubber ducky',
  'trying to eat a tin can',
  'wearing earmuffs',
  'with a daisy chain crown',
  'wearing a party hat',
  'carrying a stack of pancakes',
  'wearing a tiny backpack',
  'with a comb stuck in its quills',
  'running on a wheel powered by a tiny generator',
  'wearing a bow tie',
  'trying to operate a tiny remote control',
  'wearing pirate eye patch',
  'wearing a tiny diving helmet',
  'trying to deliver a miniature letter',
  'gnawing on a wooden ruler',
  'juggling pebbles',
  'wearing a detective trench coat',
  'trying to ride a small bicycle',
  'tangled in Christmas lights',
  'wearing oven mitts',
  'holding a tiny bouquet of flowers',
  "wearing a grandma's knitted shawl",
  'trying to use a tiny teacup',
  'wearing a diaper',
  'with painted-on polka dots',
  'trying to fit into a small car',
  'with a baby doll in its pouch',
  'hugging a teddy bear',
  'trying to read a book upside down',
  'wearing a tiny scarf and mittens',
  'balancing a ball on its nose',
  'with oversized reading glasses',
  'wearing a shower cap',
  'blowing bubbles into a tiny bubble wand',
  'wearing a life vest',
  'trying to untangle a ball of yarn',
  "wearing a tiny chef's hat",
  'leaving a trail on a miniature race track',
  'trying to carry a sugar cube bigger than itself',
  "wearing a tiny beekeeper's hat",
  'stuck in a spider web made of yarn',
  'wearing a tiny crown',
  'trying to fit into a too-small cocoon',
  'wearing tiny knitting needles',
  'holding a tiny sword',
  'wearing a tiny top hat emerging from an apple',
  'trying to light up a tiny lantern',
  'wearing a tiny bandage',
  'trying to land on a bar of soap',
  'attracted to a tiny lightbulb on a hat',
  'wearing too many tiny shoes',
]

export const generateAnimalPrompt = () => {
  const today = new Date()
  const dayOfMonth = today.getDate()
  let chosenAnimal

  if (dayOfMonth % 2 !== 0) {
    chosenAnimal = wildAnimals[Math.floor(Math.random() * wildAnimals.length)]
  } else {
    chosenAnimal =
      domesticAnimals[Math.floor(Math.random() * domesticAnimals.length)]
  }

  const chosenAssociation =
    funnyAssociations[Math.floor(Math.random() * funnyAssociations.length)]

  return `Generate an image of a ${chosenAnimal} ${chosenAssociation} with a steaming cup of coffee and include the\
  weather today in Iasi. The background should visually reflect the temperature. \
  Place the temperature in celsius degrees on the cup or in the top right.
  The text "morning coffee" should be positioned in the bottom center. \
  `
}
